# Generated by Django 2.1.3 on 2018-11-22 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_auto_20181120_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('buy_type', models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], max_length=30)),
                ('comments', models.TextField()),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Processing', 'Processing'), ('Paid', 'Paid')], max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('items', models.ManyToManyField(to='shop.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
