# Generated by Django 2.1.3 on 2018-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20181122_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buy_type',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='Pickup', max_length=30),
        ),
    ]
