# Generated by Django 2.1.3 on 2018-11-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20181126_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Processing', 'Processing'), ('Handed over', 'Handed over')], default='Accepted', max_length=100),
        ),
    ]
